config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'users#index', as: 'user'
  get '/new_user', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  post '/sessions' => 'sessions#create'
  get '/dashboard' => 'accounts#index'
  post '/dashboard/publication', to: 'accounts#create', as: 'createpub'
  get '/logout', to: 'sessions#destroy', as: 'destroy'
  get 'user/:id/edit', to: 'users#update', as: 'editform'
  post 'user/:id/edit', to: 'users#update', as: 'modifier'
  get  '*path', controller: 'application', action: 'render_404'
  post '*path', controller: 'application', action: 'render_404'
  get  '*path', controller: 'application', action: 'render_500'
  post '*path', controller: 'application', action: 'render_500'
  resources :posts, only: [:new,:create,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord

  has_many :publications
  has_secure_password

  mount_uploader :image, ImageUploader

  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def index

		@publication = Publication.new
		@publications = Publication.all
		@users = User.all 
		@user = User.find_by(id:session[:current_user_id])
		render layout: "application2"
		
	end

	def create 
		@publication = Publication.new(pub_params)
		@publication.user_id = session[:current_user_id]
		@publication.active = true

		if @publication.save
		  session[:current_publication_id] = @publication.id
		  flash[:pub_success] = "Post publié avec succès"
	      redirect_to '/dashboard'
	    else
	      flash[:pub_errors] = @publication.errors.full_messages
	      redirect_to '/dashboard'
	    end
	end

	private

	  def pub_params
	    params.require(:publication).permit(:image)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500
  
  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
  
  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

    	if @post.save
    		redirect_to dashboard_path, flash: { success: "Post was creatd successfully"}
    	else
    		redirect_to new_post_path, flash: { dander: "Post was not saved"}
    	end
	end

	def show
		
	end


	private

	def post_params


		params.require(:post).permit(:image, :image_cache)

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :authenticate_user!, only: [:show]

  def create
    @user = User.find_by(email:login_params[:email])
    if @user && @user.authenticate(login_params[:password])
      session[:current_user_id] = @user.id
      redirect_to '/dashboard'
    else
      flash[:login_errors] = ['User Name or Password is not correct']
      redirect_to '/'
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to '/'

  end

  private
    def login_params
      params.require(:login).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end

	def new
    
  	end

	def create
		@user = User.new(user_params)
		if @user.save
      		session[:current_user_id] = @user.id
      		redirect_to '/dashboard'
    	else
      		flash[:register_errors] = @user.errors.full_messages
      		redirect_to '/'
    	end
	end

	def update
	  	@user = User.find(params[:id])
	  	if @user.update(user2_params)
	  		#@user.update(surname: params[:surname])
	  		#@user.update(email: params[:email])
	  		#@user.update(image: params[:image])
	  		redirect_to '/dashboard'
  		else
  			render "accounts/edit"
  		end
  	end 


	private

	    def user_params
	      params.require(:user).permit(:name, :surname, :image, :email, :password, :password_confirmation)
	    end

	    def user2_params
	      params.require(:user).permit(:name, :surname, :image, :email)
	    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/index.html.erb
<div
      class="modal fade"
      id="publication"
      data-mdb-backdrop="static"
      data-mdb-keyboard="false"
      tabindex="-1"
      aria-labelledby="staticBackdropLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title" id="staticBackdropLabel" style="font-weight: bolder;">Nouvelle publication</h5>

            <button
              type="button"
              class="btn-close"
              data-mdb-dismiss="modal"
              aria-label="Close"
            ></button>

          </div>

          <div class="modal-body">

            
            <%= form_with(model: @publication, url: createpub_path, method: "post") do |form| %>
                
                <div class="form-outline mb-4">
                
                <%= image_tag(@publication.image.url) if @publication.image && @publication.image.url %>
                  <%= form.file_field :image, class: "form-control" %>
                  
                </div>

                
                
                
              <div class="text-center">
                <%= form.submit "Publier", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              <% end %>
              </div>
              <hr>
              &nbsp;&nbsp;
                    <%= link_to "Sign In", user_path, class: "btn btn-outline-success" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-mdb-dismiss="modal">
              Annuler
            </button>
            
          </div>
        </div>
      </div>
    </div>





<div class="errors">
      <% if flash[:pub_errors]%>
        <% flash[:pub_errors].each do |error| %>
          <p class="alert alert-danger"> <%=error%></p>
        <%end%>
      <%end%>
</div>

<div class="errors">
      <% if flash[:pub_success]%>
        
          <p class="alert alert-success"> <%= flash[:pub_success] %></p>
        <%end%>
      
    </div>


<div style="margin-top: 50px;">
<% @publications.each do |publication| %>
  
<div class="row">
  <div class="col-md-1">
    
  </div>

  <div class="col-md-7 mb-3">
      <div class="card mb-3">

    <p class="card-text mt-3">
        &nbsp;&nbsp;&nbsp;
      <i class="fas fa-user"></i>
        &nbsp;
        <% @users.each do |usere| %>
          <% if publication.user_id == usere.id %>
              <%= usere.name %>&nbsp;&nbsp;
              <%= usere.surname %>
          <% end %>
        <% end %>
        </p>
        <div class="card-body">
          <img
            src="<%= publication.image %>"
            class="card-img-top"
            alt="..."
          />
        </div>
     
    <div class="card-body">
      
      <p class="card-text text-center" style="margin-top: -15px;">
       
      <div class="row">
        <div class="col-6 ">
          <p class="card-text">
            <small class="text-muted">Publié le <%= publication.created_at %></small>
          </p>
          <br>
          
        </div>
        
      </div>

    </div>

        
</div>
  </div>

  <div class="col-md-3">
      
  </div>

</div>

<% end %>

</div>

app/views/instagram/index.html.erb
<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

<div class="field">
  <%= form.label :image %>
  <%= form.text_area :image %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Instagram</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <meta name="viewport" content="width=device-width,initial-scale=1">

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <!-- MDB -->
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet"
        />
    </head>
  <body style="background: #fafafa !important;">

    <nav class="navbar navbar-expand-lg navbar-blue  mb-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">
        <div class="container">
            <a class="navbar-brand" href="#">Instagram</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    
                    
                    <a href="" data-toggle="collapse" aria-expanded="false" class="btn btn-success" data-mdb-toggle="modal"
                    data-mdb-target="#inscription">Sign Up</a>          
            
                </ul>
            </div>
        </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer class="bg-light text-center text-lg-start ">
      <!-- Copyright -->
      <div class="text-center p-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">
        © 2020 Copyright:
        <a class="text-dark" href="/">Instagram</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
  </body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Instagram</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <meta name="viewport" content="width=device-width,initial-scale=1">

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <!-- MDB -->
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    </head>
  <body style="background: #fafafa !important;">

    <nav class="navbar navbar-expand-lg navbar-blue fixed-top mb-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">
        <div class="container">
            <a class="navbar-brand" href="#">Instagram</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    
                    <a href="" data-toggle="collapse" aria-expanded="false" class="btn btn-success" data-mdb-toggle="modal"
                data-mdb-target="#publication">Nouvelle publication</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                <div style="padding-left: 119px; border-left: solid 2px whitesmoke;">
                  <h4 style="color: whitesmoke;">Profil</h4>
                </div>
                        
                </ul>
            </div>
        </div>
    </nav>


    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3 style="font-weight: bold;"></h3>
            </div>

              <div class="text-center">
                <% if @user.image.blank? %>
                    <img
                    src="https://mdbootstrap.com/img/new/standard/city/047.jpg"
                    class="img-fluid rounded-circle"
                    alt=""
                    style="height: 120px; width: 120px; margin-top: 35px;"
                />
                <% else %>
                    <img
                      src="<%= @user.image %>"
                      class="img-fluid rounded-circle"
                      alt=""
                      style="height: 120px; width: 120px; margin-top: 30px;"
                    />
                <% end %>
                

                <h4 style="margin-top: 15px;"><%= @user.name %>&nbsp;&nbsp;<%= @user.surname %></h4>

                <h6><%= @user.email %></h6>

                <h5 style="margin-top: 30px;">Publications :&nbsp;<%= @user.publications.count %></h5>

              </div>

              <div class="list-unstyled text-center" style="margin-top: 20px;">
                <li >
                    <a href="" data-toggle="collapse" aria-expanded="false" class="btn btn-success" data-mdb-toggle="modal"
                data-mdb-target="#update">Update</a>
                </li>
              </div>

            
            <ul class="list-unstyled text-center" style="margin-top: 50px;">

                
                <li >
                    <%= link_to "Log Out", destroy_path, method: :delete, class: "btn btn-danger "%>
                    
                </li>
                
            </ul>

            
        </nav>

        
        
            
    </div>


    

    <p class="alert alert-danger"><%= flash[:notice] %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

   

<div
      class="modal fade"
      id="update"
      data-mdb-backdrop="static"
      data-mdb-keyboard="false"
      tabindex="-1"
      aria-labelledby="staticBackdropLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title" id="staticBackdropLabel" style="font-weight: bolder;">Nouvelle publication</h5>

            <button
              type="button"
              class="btn-close"
              data-mdb-dismiss="modal"
              aria-label="Close"
            ></button>

          </div>

          <div class="modal-body">

            
            <%= form_with(model: @user,url: modifier_path(@user), method: "post") do |form| %>
                
                
                <div class="form-outline mb-4">
                  <%= form.label :name, "First Name", class: "form-label"%> <br>
                  <%= form.text_field :name, class: "form-control"%>  
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :surname, "Last Name", class: "form-label" %> <br>
                  <%= form.text_field :surname, class: "form-control" %>  
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :email, "Email", class: "form-label" %> <br>
                  <%= form.email_field :email, class: "form-control" %>  
                </div>
                <div class="form-outline mb-4">
                  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
                  <%= form.file_field :image, class: "form-control" %>
                </div>
                
                
                <div class="text-center">
                <%= form.submit "Valider", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              
                </div>
            <% end %>
        </div>
              

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-mdb-dismiss="modal">
              Annuler
            </button>
            
          </div>
        </div>
      </div>
    <footer class="bg-light text-center text-lg-start ">
      <!-- Copyright -->
      <div class="text-center p-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">
        © 2020 Copyright:
        <a class="text-dark" href="/">Instagram</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
  </body>
</html>


 

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login & Registration</title>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body>

    <div
      class="modal fade"
      id="inscription"
      data-mdb-backdrop="static"
      data-mdb-keyboard="false"
      tabindex="-1"
      aria-labelledby="staticBackdropLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title" id="staticBackdropLabel" style="font-weight: bolder;">Sign Up !</h5>

            <button
              type="button"
              class="btn-close"
              data-mdb-dismiss="modal"
              aria-label="Close"
            ></button>

          </div>

          <div class="modal-body">

                
                <div class="form-outline mb-4 text-center">
                  
                  <form action="/users" method="POST">
                    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>"><br><br>
                    <div class="form-outline mb-4">
                      <input type="text" id="nom" class="form-control" name="user[name]" />
                      <label class="form-label" for="nom">First Name</label>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="text" id="nom" class="form-control" name="user[surname]" />
                      <label class="form-label" for="nom">Last Name</label>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="email" id="email" class="form-control" name="user[email]" />
                      <label class="form-label" for="email">Email</label>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="password" id="password" class="form-control" name="user[password]" />
                      <label class="form-label" for="password">Password</label>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="password" id="confirmation_password" class="form-control" name="user[password_confirmation]" />
                      <label class="form-label" for="confirmation_password">Password Confirmation</label>
                    </div>


                    
                    <input type="submit" name="Submit" class="btn btn-success" value="Sign Up" style= "padding-right: 50px; padding-left: 50px; font-size: 17px;">
                  </form>
                </div>
                             

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger" data-mdb-dismiss="modal">
              Annuler
            </button>
            
          </div>
        </div>
      </div>
    </div>

    <div class="errors">
      <% if flash[:login_errors]%>
        <% flash[:login_errors].each do |error| %>
          <p class="alert alert-danger"> <%=error%></p>
        <%end%>
      <%end%>
    </div>

    <div class="errors">
      <% if flash[:register_errors]%>
        <% flash[:register_errors].each do |error| %>
          <p class="alert alert-danger"> <%=error%></p>
        <%end%>
      <%end%>
    </div>

    <div class="container">
        <div class="text-center mt-5">
            <h3>Welcome to Instagram</h3><br><br>
            
            <div class="container mt-44">
              <div class="row">

                <div class="col-md-1">

                </div>
                <div class="col-md-4 mt-5 text-center card-body">
                  
                  
                </div><div class="col-md-1">

                </div>
                <div class="col-md-4 mb-5 text-center card-body">
                  <h1>
                    Sign In !
                  </h1>

                  <form action="/sessions" method="POST">
                    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>"><br><br>

                    <div class="form-outline mb-4">
                      <input type="email" id="email" class="form-control" name="login[email]" />
                      <label class="form-label" for="nom">Email</label>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="password" id="password" class="form-control" name="login[password]" />
                      <label class="form-label" for="password">Password</label>
                    </div>
                    <input type="submit" name="Submit" class="btn btn-success" value="Sign In" style= "padding-right: 50px; padding-left: 50px; font-size: 17px;">
                  </form>                  

                </div>
                <div class="col-md-2">

                </div>

              </div>
            </div>

        </div>
    </div>

    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
  </body>
</html>